### PR TITLE
Add more client extensions, allow client creation with refresh token

### PR DESCRIPTION
**Pull request by ginach**

### CODE REVIEW

**Comment by aclev** [comment]
:+1:

**Comment by artwang** [comment]
From the GetSilentlyAuthenticatedMicrosoftAccountClient(), it requires a refresh token. Can you show us how to obtain a refresh token? Thanks.

**Comment by MarcorOnline** [comment]
@artwang any news about how to obtain a refresh token? I've added the scope "wl.offline_access" to GetAuthenticatedClientUsingWebAuthenticationBroker but I obtain a null RefreshToken :(

**Comment by artwang** [comment]
I think I figured it out. This is what I do.

For the first time login, you include "wl.offline_access" in your scope and call the following,

OneDriveClient.GetMicrosoftAccountClient(clientId, returnUrl, scopes, webAuthenticationUi: new FormsWebAuthenticationUi());
if (!this.oneDriveClient.IsAuthenticated)
{
    AccountSession session = await this.oneDriveClient.AuthenticateAsync();
    this.refreshToken = session.RefreshToken; // store the refreshToken somewhere for later use
}

The 2nd time around (you can check if this.refreshToken has value), you can simply call (as ginach suggested)

await OneDriveClient.GetSilentlyAuthenticatedMicrosoftAccountClient(
    clientId,
    returnUrl,
    scopes,
    this.refreshToken);

Hope this will help.

**Comment by MarcorOnline** [comment]
@artwang thanks for your help, I'm on a Windows 10 UWP, what's the returnUrl ? can I omit the webAuthenticationUi ?

I tried:
var scopes = new string[] { "wl.signin", "wl.offline_access", "onedrive.readwrite" };

var oneDriveClient = OneDriveClientExtensions.GetClientUsingWebAuthenticationBroker(clientId, scopes);
                        AccountSession session = await oneDriveClient.AuthenticateAsync();
                        var refreshToken = session.RefreshToken;

but the RefreshToken is null...

thanks

**Comment by artwang** [comment]
Sorry, I have not done this with UWP.

**Comment by ginach** [comment]
Issue #44 is tracking the fact that the refresh token isn't being returned via GetClientUsingWebAuthenticationBroker. My current PR into master has a fix for this. After the fix, the code above would be the correct approach in UWP.

**Pull request merged**
